version: '3'
services:
    integration_test:
      build:
          context: ./
          dockerfile: Dockerfile.test
      volumes:
        - .:/app
      depends_on:
        - web_app
      links:
        - web_app
      environment:
        - FLASK_ENV=docker
      command: ["bash", "-c", "sleep 10 && py.test && find . -name __pycache__ -delete"]
    web_app:
      build:
          context: ./
          dockerfile: Dockerfile
      volumes:
        - .:/app
      ports:
        - "5000"
      depends_on:
        - redis
        - postgres
      links:
        - redis
        - postgres
      environment:
        - FLASK_ENV=docker
        - REDIS_HOST=redis
      command: ["python", "run_test_mode.py"]
    redis:
        image: redis:latest
        ports:
          - "6379"
    postgres:
        image: postgres:latest
        ports:
          - "5432"
